name: notifications_repo
description: Repository responsible for notifications
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.0.0
  local_data:
    git:
      url: https://gitlab+deploy-token-4:4zjU2bJymy7c6vTztanf@gitlab.probasegroup.com/flutter_packages/local_data.git
      ref: 25bcb3354fc6171858c62e33d81410192458969f
  net_source:
    path: ../net_source
  permission_client:
    path: ../permission_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
