name: net_source
description: Package to handle network calls
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^7.0.0
dependencies:
  dio: ^5.3.3
  internet_connection_checker: ^3.0.1
  phoenix_socket: ^0.7.6
